config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  root to: "home#index"
  # root :to => "home#index"

  resources :users, :only => [:index] do
    resources :images do
      member do
        put "like", to: "images#upvote"
      end
    end
  end
  resources :users, :only => [:show] do
    resources :tags

  end
  resources :images do


  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ActiveRecord::Base

  has_attached_file :paperclip, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :paperclip, :content_type => /\Aimage\/.*\Z/

  has_many :tags
  has_many :users, through: :tags
  acts_as_votable

  validates :owner_id, :presence => true

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :image
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tags
  has_many :images, through: :tags

 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
 validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @images = Image.all
    if current_user
      @user = current_user.id
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @image = Image.new
    @images = Image.where(owner_id: current_user.id)
    @user = current_user.id
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(paperclip: image_params[:paperclip], owner_id: current_user.id)
    if @image.save
      redirect_to images_path
    else
      render :back
    end
  end

  def show
    @user = current_user.id
    @image = Image.find(params[:id])
  end

  def edit
    @user = current_user.id
    @image = Image.find(params[:id])
  end

  def update
    @user = current_user.id
    @image = Image.find(params[:id])
    if @image.update(user_ids: tag_params[:user_ids])
      redirect_to :back
    else
      render :edit
    end
  end

  def destroy
    @user = current_user.id
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to user_images_path
  end

  def upvote
    @image = Image.find(params[:id])
    @image.upvote_by current_user
    redirect_to :back
  end

private
  def image_params
    params.require(:image).permit(:paperclip)
  end

  def tag_params
    params.require(:image).permit({user_ids: []})
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

protected
  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def create
    @user = User.create( user_params )
  end


  private

  def user_params
    params.require(:user).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>welcome to fakrFlickr</h1>
<% if user_signed_in? %>
  <%= link_to "Personal Photo Gallery", user_images_path(@user, @images) %>
<% end %>
<br>
<% @images.each do |image| %>
  <%= link_to image_tag(image.paperclip), user_image_path(image.owner_id, image) %>
<% end %>

app/views/images/_form.html.erb
<%= render "layouts/errors", :object => @image %>

<%= form_for @image, url: images_path, html: { multipart: true } do |form| %>
  <%= form.label :paperclip, "New Image" %>
  <%= form.file_field :paperclip %>
  <%= form.submit %>
<% end %>

app/views/images/edit.html.erb
<h2>Edit Image</h2>

<%= render "form" %>

app/views/images/index.html.erb
<h2>Personal Photo Gallery</h2>
<%= link_to "Add New Image", new_user_image_path(@user) %>
<br>
<br>

<% @images.each do |image| %>
  <%= link_to image_tag(image.paperclip), user_image_path(@user, image) %>
<% end %>

<%= link_to "View All Photos", root_path %>

app/views/images/new.html.erb
<h2>Add New Image</h2>

<%= render "form" %>

app/views/images/show.html.erb
<h1>Image Page</h1>

<%= image_tag @image.paperclip %>
<br>

<%= link_to like_user_image_path(@image), method: :put do %>
  <button class="btn">Add Favorite Vote</button>
  <h5>Total Votes: <%= @image.get_upvotes.size %></h5>
<% end %>

<h5>Users Tagged in Photo: </h5>
<% @image.users.each do |user| %>
  <%= user.email %>
<% end %>
<br>

<h4>Tag Friends with Profile Accounts</h4>
<%= simple_form_for(@image) do |f| %>
  <%= f.association :users, collection: User.all, label_method: :email,  as: :check_boxes %>
  <%= f.button :submit %>
<% end %>
<br>

<% if user_signed_in? %>
  <% if current_user.id == @image.owner_id %>
    <p><%= link_to "Edit", edit_user_image_path(@user, @image) %></p>
    <p><%= link_to "Delete Image", user_image_path(@user, @image), :data => {:confirm => "REALLY???", :method => "delete"} %></p>
  <% end %>
<% end %>

<%= link_to "View All Photos", root_path %><br>
<%= link_to "View My Photos", user_images_path(@user) %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
 <% object.errors.full_messages.each do |message| %>
   <li><%= message %></li>
 <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flickr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">FakrFlickr</a>
        <% if user_signed_in? %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            Logged in as <%= current_user.email %>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Log-out', destroy_user_session_path, method: :delete %></li>
            <li class="round-image-50"><%= image_tag current_user.avatar.url(:thumb) %></li>
          </ul>
        <% else %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
          </ul>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>